name: OpenWrt k2p CI
on:
  schedule:
    - cron:  0 7 * * 5
  push:
    branches:
      - master
    paths:
      - '.config.openwrt'
      - '.github/workflows/k2p-build.yml'

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout - clone repository
      uses: actions/checkout@v2

    - name: Install - system build dependencies
      run: |
        sudo swapoff /swapfile || echo "no swapfile"
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc || echo "clean partly"
        sudo -E apt-get -qq update
        sudo -E apt-get -yqq install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
        sudo -E apt-get -yqq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download - openwrt source download
      run: |
        git clone -b openwrt-19.07 https://github.com/openwrt/openwrt.git
        
    - name: Update - openwrt source update and install 
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Clone - openwrt plugin source
      run: |
        cd openwrt
        git clone https://github.com/MeIsReallyBa/k2p-openwrt-mt7615_5.0.2.0 package/mtk

    - name: Config - official openwrt k2p build config
      run: |
        cp .config.openwrt openwrt/.config
        cd openwrt
        make defconfig

    - name: Download - openwrt build dependencies
      run: |
        cd openwrt
        make download -j8

    - name: Build - make openwrt source
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Remove - delete packages files
      run: |
        cd openwrt/bin/targets/ramips/mt7621/
        rm -rf packages/
        ls -hl

    - name: Upload - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: openwrt-k2p
        path: openwrt/bin/targets/ramips/mt7621/
